<a href="https://colab.research.google.com/github/ak7109162-wq/Pandas_python_Library_fullNotes-/blob/main/Pandas_class6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [ ]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age" : [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [ ]:
print(df.groupby("Department")["Salary"].mean() )# har department ka average Average salary

count_Employees = df.groupby("Department")["Employee"].count() # Har department mei kitne log hai
print(count_Employees)

multi_stats = df.groupby("Department")["Salary"].agg(["mean","min","max"])
print(multi_stats)

# Department wise average age.
print(f"Average of department are : {df.groupby("Department")["Age"].mean()}")

# df.groupby("Department").agg({column:ispe lagana kya hai mean,min,max,count ?})
print(df.groupby("Department").agg(
    {"Salary" : ["mean","min","max"],
    "Age" : ["min","max"]}
    ))

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64
Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64
                    mean    min    max
Department
Finance     61000.000000  58000  65000
HR          51000.000000  50000  52000
IT          72333.333333  70000  75000
Average of department are : Department
Finance    29.333333
HR         28.500000
IT         31.000000
Name: Age, dtype: float64
                  Salary               Age
                    mean    min    max min max
Department
Finance     61000.000000  58000  65000  26  35
HR          51000.000000  50000  52000  28  29
IT          72333.333333  70000  75000  30  32

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [ ]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [ ]:
#df.pivot_table(index= "konsa column hai", values = kya chaihiye,aggfunc=mean,min,max,count)

print(df.pivot_table(index="Department",values="Salary",aggfunc="mean"))

print(df.pivot_table(index="Department", values=["Salary", "Age"], aggfunc="mean"))

# Age Group--> 25-30,31-35
df["Age_Group"] = pd.cut(df["Age"],bins=[25,30,35,40],labels=["25-30","31-35","36-40"])
pd.crosstab(df["Department"],df["Age_Group"])

                  Salary
Department
Finance     61000.000000
HR          51000.000000
IT          72333.333333
                  Age        Salary
Department
Finance     29.333333  61000.000000
HR          28.500000  51000.000000
IT          31.000000  72333.333333

Age_Group   25-30  31-35
Department
Finance         2      1
HR              2      0
IT              1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [ ]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City

# 2. Group by Department to get average Salary and max Age
# Write your code here

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here

# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here

# 5. Build a crosstab for Department vs City
# Write your code here

In [ ]:
import pandas as pd
import numpy as np
data = {
    "Department" : ["HR","IT","Finance","IT","HR","Finance","IT","IT","HR"],
    "Employee" : ["john","pitter","Alice","Mike","Olivia", "Emma", "Charlotte", "Grace", "Elizabeth"],
    "Salary" : [5000,10000,12000,15000,18000,19000,20000,21000,22000],
    "Age" : [25,28,30,35,45,40,45,48,52],
    "City" : ["Bhopal","patna","Mumbai","patna","Bhopal","Mumbai","patna","patna","Bhopal"]
}
df = pd.DataFrame(data)

In [ ]:
# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
print(df)

# 2. Group by Department to get average Salary and max Age
# Write your code here
print(df.groupby("Department").agg({"Salary":"mean","Age":"max"}))

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
# Write your code here

print(df.groupby("Department").agg(
    Average_Salary = ("Salary","mean"),
    Max_Age = ("Age","max")
    ))


# 4. Create a pivot_table to see mean Salary by Department and City
# Write your code here

print(df.pivot_table(index="Department",columns="City",values="Salary",aggfunc="mean"))

# NOTE--> df.pivot_table(index= "konsa column hai", values = kiska values chaihiye,aggfunc=mean,min,max,count)


# 5. Build a crosstab for Department vs City
# Write your code here

#pd.crosstab() is used to create a frequency table (count table) between two or more categorical variables.

pd.crosstab(df["Department"],df["City"]) # mtlb department me jao aur kon sa department kitni
# bar kis city me aa raha haii uska frequency count karo

  Department   Employee  Salary  Age    City
0         HR       john    5000   25  Bhopal
1         IT     pitter   10000   28   patna
2    Finance      Alice   12000   30  Mumbai
3         IT       Mike   15000   35   patna
4         HR     Olivia   18000   45  Bhopal
5    Finance       Emma   19000   40  Mumbai
6         IT  Charlotte   20000   45   patna
7         IT      Grace   21000   48   patna
8         HR  Elizabeth   22000   52  Bhopal
             Salary  Age
Department
Finance     15500.0   40
HR          15000.0   52
IT          16500.0   48
            Average_Salary  Max_Age
Department
Finance            15500.0       40
HR                 15000.0       52
IT                 16500.0       48
City         Bhopal   Mumbai    patna
Department
Finance         NaN  15500.0      NaN
HR          15000.0      NaN      NaN
IT              NaN      NaN  16500.0

City        Bhopal  Mumbai  patna
Department
Finance          0       2      0
HR               3       0      0
IT               0       0      4

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.