<a href="https://colab.research.google.com/github/ak7109162-wq/Pandas_python_Library_fullNotes-/blob/main/pandas_class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [ ]:
import pandas as pd
a = {
    "Name":["Devraj","Bob","charlie","David","Emma"],
    "Age" : [25,30,35,40,22],
    "Score" : [80,92,79,85,95]
}
b = pd.DataFrame(a)
#1. select single column
b[b["Age"] > 27]  # ye true wala value print karega{boolean index dega}

#2. selecting single column score > 85
b[b["Score"] > 85]

# 3. Multiple conditions (AND): Age > 27 AND Score > 85

b[(b["Age"] > 27) & (b["Score"] > 85)]

#4. Multiple conditions (oR) : Age  > 27 OR Score > 85 {dono me se koi ek
# conditio satisfy honi chaiye}

(b["Age"] > 27) | (b["Score"] > 85) # yedi aise likhte hai to result boolean me
b[(b["Age"] > 27) | (b["Score"] > 85)] # isme me sare elemt print kar denge



#5. Not(~)
b[~(b["Score"] > 85)]

# Age

      Name  Age  Score
0   Devraj   25     80
2  charlie   35     79
3    David   40     85

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [ ]:
#1 . Age > 25 ANN Score > 85
b[(b["Age"] > 35) & (b["Score"])]
#2. Age < 35 or Score >= 90
b[(b["Age"] < 35) | (b["Score"] >= 90)]

#3. Age between 25 and 35 (inclusive)
b[(b["Age"] >= 25) & (b["Age"] <= 35)]

      Name  Age  Score
0   Devraj   25     80
1      Bob   30     92
2  charlie   35     79

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [ ]:
# Simple Query : Age > 25
print(b.query("Age > 25"))

#2. Multiple condition using query : Age < 35 and score >= 85
print(b.query("Age < 35 and Score >= 85 "))

#3. Multiple condition using query : Age >= 30 and score >= 90
print(b.query("Age >= 30 and Score >= 90"))

# 4. Threshold(@)
score = 90 # Variable
b.query("Score >= @score") # 90 se bara jiska score hai o print ho jay

      Name  Age  Score
1      Bob   30     92
2  charlie   35     79
3    David   40     85
   Name  Age  Score
1   Bob   30     92
4  Emma   22     95
  Name  Age  Score
1  Bob   30     92

   Name  Age  Score
1   Bob   30     92
4  Emma   22     95

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [ ]:
print(b)

#1. convert name to lowercase().
print(b["Name"].str.lower())

#2. convert name to uppercase().
print(b["Name"].str.upper())

#3. Title() -> capatialize first letter of all the words.
print(b["Name"].str.title())

#4. Replace a substracting("OldString","NewString")
b["Name"].str.replace("charlie","Charlies")

#5. check if Name column contains the letter
b[b["Name"].str.contains("a")]

#6. .startwith("Letter") --> letter starting with.
b[b["Name"].str.startswith("D")]

#7. .endswith("Letter") --> letter ending with.
b[b["Name"].str.endswith("e")]

      Name  Age  Score
0   Devraj   25     80
1      Bob   30     92
2  charlie   35     79
3    David   40     85
4     Emma   22     95
0     devraj
1        bob
2    charlie
3      david
4       emma
Name: Name, dtype: object
0     DEVRAJ
1        BOB
2    CHARLIE
3      DAVID
4       EMMA
Name: Name, dtype: object
0     Devraj
1        Bob
2    Charlie
3      David
4       Emma
Name: Name, dtype: object

      Name  Age  Score
2  charlie   35     79

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

In [ ]:
import pandas as pd
data = {
    "Name" : ["Ratan singh","Bhagat singh","Himmat singh","Bharat Tiwari"],
    "Age" : [28,23,26,32],
    "city" : ["patna","Mumbai","delhi","Ara"],
    "Score" : [89,90,87,76]
}
df = pd.DataFrame(data)

#1.  Build a DataFrame with columns: Name, Age, City, Score
print(df)

#2. Use boolean indexing to select rows where Age > 25
# Write your code here
print(df[df["Age"] > 25])

#3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here
print(df[(df["city"] == "Mumbai") | (df["city"] == "delhi")])

# 4. Use query() to find rows with Score >= 85 and Age < 35

print(df.query("Score >= 80 and Age < 25 "))


# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

df["city"].str.lower() # [str.lowercase] ka main work hai small letter me
# change karna
df["city"].str.replace("delhi","New Delhi")

            Name  Age    city  Score
0    Ratan singh   28   patna     89
1   Bhagat singh   23  Mumbai     90
2   Himmat singh   26   delhi     87
3  Bharat Tiwari   32     Ara     76
            Name  Age   city  Score
0    Ratan singh   28  patna     89
2   Himmat singh   26  delhi     87
3  Bharat Tiwari   32    Ara     76
           Name  Age    city  Score
1  Bhagat singh   23  Mumbai     90
2  Himmat singh   26   delhi     87
           Name  Age    city  Score
1  Bhagat singh   23  Mumbai     90

0        patna
1       Mumbai
2    New Delhi
3          Ara
Name: city, dtype: object

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.